### PR TITLE
Add channel selection and config improvements

### PR DESCRIPTION
**Pull request by willhlaw**
### FEATURES

- Add select option for user to choose the channel to post slackblast to but default initial value based on any slashcommand user input or .env CONFIG

    - If user supplies channel name after slashhcommand, then default to post to that channel
    - If .env CONFIG=USER, then default to post directly to user's channel
    - if .env CONFIG=THE_AO, then default to post to the selected AO in the modal
    - if .env CONFIG=<channel-id>, then default to post to the preconfigured channel
 
- Add specific_channel to read slash command passed in from slack as "text" param
    - Ex: /slackblast [#channel - defaults to #back_blasts] will post back to #channel

- Add "/backblast" along with "slackblast" as a command

### IMPROVEMENTS

- Add .env-f3nation-community with local development tips with ngrok 
- Ignore Azure publish yml file that will be F3 region specific
- Add gunicorn.conf.py so that Azure App Service does not need to set special startup command
- Remove PORT from .env
- Update README

### CODE REVIEW

**Review by wolfpackt99 — APPROVED** [review]
🔥 - solid improvements from my hackery at python!

**Comment by willhlaw** [comment]
@all-contributors please add @wolfpackt99 for ideas, code, doc, mentoring, and review

**Comment by willhlaw** [comment]
@all-contributors please add @yankeestom  for ideas, code, and review

**Comment by willhlaw** [comment]
@all-contributors please add @willhlaw for ideas, code, doc, and projectManagement

**Pull request merged**
